### ISSUE TITLE
when destroying : TypeError: load_config() takes exactly 3 arguments (2 given)

### ISSUE THREAD

**Issue by msimonin** [BeyondTheClouds/enos#178]
+ enos destroy --hard
INFO:root:Destroying all the resources
INFO:root:Loaded provider <module 'enos.provider.g5k' from '/tmp/workspace/enos-g5k-params/enos/provider/g5k.pyc'>
ERROR:root:Exception
Traceback (most recent call last):
  File "/tmp/workspace/enos-g5k-params/enos/utils/enostask.py", line 77, in decorated
    fn(*args, **kwargs)
  File "/tmp/workspace/enos-g5k-params/enos/utils/enostask.py", line 103, in decorator
    return fn(*args, **kwargs)
  File "/tmp/workspace/enos-g5k-params/enos/enos.py", line 595, in destroy
    provider.destroy(env)
  File "/tmp/workspace/enos-g5k-params/enos/provider/g5k.py", line 57, in destroy
    conf = load_config(env['config'], self.default_config())
TypeError: load_config() takes exactly 3 arguments (2 given)
Finished: SUCCESS

**Comment by msimonin** [comment]
see
https://github.com/BeyondTheClouds/enos/blob/417b3caf2c866e6a90d0b86070942029ed11332b/enos/provider/g5k.py#L57
load_config shouldn't be used here (beside the problem with the parameters), only the provider config should be used. It should be accessible through `env['config']['provider']`.
