### ISSUE TITLE
[g5k] WANWide scenario deployment problem in Rennes site

### ISSUE THREAD

**Issue by daespinel** [BeyondTheClouds/enos#241]
# Context
Following the tutorial _Benchmarking OpenStack with EnOS_ available at: http://enos.irisa.fr/tp-g5k/ to deploy a WANWide scenario using traffic shaping, I have encountered some errors while trying to deploy in Rennes site.

# Workflow
Full `reservation.yaml` file with enos **stable/pike**
```
---
# ############################################### #
# Grid'5000 reservation parameters                #
# ############################################### #
provider:
  type: g5k
  name: 'Enos'
  walltime: '04:00:00'
  # mandatory : you need to have exacly one vlan
  vlans:
     rennes: "{type='kavlan'}/vlan=1"
  # Be less strict on node distribution especially
  # when nodes are missing in the reservation
  # or not deployed
  role_distribution: debug
  env_file: /home/discovery/enos_env/debian9-x64-enos-nfs.env

# Topology description
topology:
  grp1:
    paravance:
      control: 1
      compute: 2
      network: 1
  grp2:
    paravance:
      compute: 2

network_constraints:
  enable: true
  default_delay: 25ms
  default_rate: 100mbit
  default_loss: 0.1%
  constraints:
    - src: grp1
      dst: grp2
      delay: 50ms
      rate: 1gbit
      loss: 0%
      symetric: true


# ############################################### #
# Inventory to use                                #
# ############################################### #

# This will describe the topology of your services
inventory: inventories/inventory.sample

# ############################################### #
# docker registry parameters
# ############################################### #

# A registry will be deployed and used during the deployment
registry:
  type: none

# ############################################### #
# Enos Customizations                             #
# ############################################### #
enable_monitoring: yes

# ############################################### #
# Kolla parameters                                #
# ############################################### #
# Repository
kolla_repo: "https://git.openstack.org/openstack/kolla-ansible"
kolla_ref: "stable/pike"

# Vars : globals.yml
kolla:
  kolla_base_distro: "centos"
  kolla_install_type: "source"
  docker_namespace: "beyondtheclouds"
  enable_heat: "no"
#  node_custom_config: "{{cwd}}/patch"
#  enable_dvr: "yes
```
using the command: `enos deploy -f reservation.yaml -vv`

# Expected Behavior
Successful enos deployment of OpenStack 

# Current Behavior
Installation not finishing and showing the next output:
```
2018-05-29 14:34:53,827 INFO: Setting ['paravance-66-eth1.rennes.grid5000.fr', 'paravance-67-eth1.rennes.grid5000.fr', 'paravance-64-eth1.rennes.grid5000.fr', 'paravance-68-eth1.rennes.grid5000.fr', 'paravance-63-eth1.rennes.grid5000.fr', 'paravance-65-eth1.rennes.grid5000.fr'] in vlan 4 of site rennes
INFO:execo:Setting ['paravance-66-eth1.rennes.grid5000.fr', 'paravance-67-eth1.rennes.grid5000.fr', 'paravance-64-eth1.rennes.grid5000.fr', 'paravance-68-eth1.rennes.grid5000.fr', 'paravance-63-eth1.rennes.grid5000.fr', 'paravance-65-eth1.rennes.grid5000.fr'] in vlan 4 of site rennes
Traceback (most recent call last):
  File "/home/daespinel/enos/venv/bin/enos", line 11, in <module>
    load_entry_point('enos', 'console_scripts', 'enos')()
  File "/home/daespinel/enos/enos/enos.py", line 794, in main
    deploy(**docopt(deploy.__doc__, argv=argv))
  File "/home/daespinel/enos/enos/utils/enostask.py", line 77, in decorated
    fn(*args, **kwargs)
  File "/home/daespinel/enos/enos/enos.py", line 686, in deploy
    up(**kwargs)
  File "/home/daespinel/enos/enos/utils/enostask.py", line 77, in decorated
    fn(*args, **kwargs)
  File "/home/daespinel/enos/enos/enos.py", line 134, in up
    provider.init(config, kwargs['--force-deploy'])
  File "/home/daespinel/enos/enos/provider/g5k.py", line 50, in init
    vlans)
  File "/home/daespinel/enos/enos/provider/g5k.py", line 314, in _mount_cluster_nics
    vlan)
  File "/home/daespinel/enos/venv/local/lib/python2.7/site-packages/execo_g5k/api_utils.py", line 714, in set_nodes_vlan
    return _get_g5k_api().post('/sites/%s/vlans/%s' % (site, str(vlan_id)), json.dumps({"nodes": network_addresses}))
  File "/home/daespinel/enos/venv/local/lib/python2.7/site-packages/execo_g5k/api_utils.py", line 203, in post
    raise APIException(uri, 'POST', response, content)
execo_g5k.api_utils.APIException: <APIException uri=u'https://api.grid5000.fr/3.0/sites/rennes/vlans/4' method=POST response={'status': '401', 'content-length': '463', 'server': 'Apache/2.4.25 (Debian)', 'date': 'Tue, 29 May 2018 12:34:53 GMT', 'content-type': 'text/html; charset=iso-8859-1', 'www-authenticate': 'Basic realm="Grid\'5000 API"'} content='<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">\n<html><head>\n<title>401 Unauthorized</title>\n</head><body>\n<h1>Unauthorized</h1>\n<p>This server could not verify that you\nare authorized to access the document\nrequested.  Either you supplied the wrong\ncredentials (e.g., bad password), or your\nbrowser doesn\'t understand how to supply\nthe credentials required.</p>\n<hr>\n<address>Apache/2.4.25 (Debian) Server at api.grid5000.fr Port 443</address>\n</body></html>\n'>
```

**Comment by daespinel** [comment]
Yes, I'm running inside a dedicated node, but this is not happening in other sites (Successfully tested in Nancy and Lyon), so it's a special measure that have to be done in Rennes?

**Comment by rcherrueau** [comment]
This is not supposed to work on other sites, but sometimes, G5k moves in mysterious ways ...

There is a G5k issue on that specific topic:  https://intranet.grid5000.fr/bugzilla/show_bug.cgi?id=8862

**Comment by msimonin** [comment]
@daespinel If it's working on other sites, you can still launch the deployment from there and actually deploy in Rennes.

**Comment by daespinel** [comment]
@rcherrueau thanks, is this authentication code in enos documentation (I didn't find it)? @msimonin did you mean using a dedicated node inside another site (ex. Nancy) to deploy in Rennes?

**Comment by msimonin** [comment]
@daespinel is it ok ?

**Comment by daespinel** [comment]
@msimonin yes, after adding the codding for authentication, the deployment is working like a charm, thank you

**Comment by rcherrueau** [comment]
Good
