### ISSUE TITLE
shaker benchs failed complaining that shaker-image does not exist 

### ISSUE THREAD

**Issue by rcherrueau** [BeyondTheClouds/enos#288]
Indeed, Shaker failed to build the image. Here is the error trace:
```
INFO shaker.engine.all_in_one [-] Building the image
INFO shaker.openstack.clients.openstack [-] Connection to OpenStack is initialized
INFO shaker.engine.image_builder [-] Using existing flavor: m1.medium
INFO shaker.engine.image_builder [-] Detected build mode is "heat"
INFO shaker.engine.utils [-] Alias "ubuntu" is resolved into file "/usr/local/lib/python3.5/site-packages/shaker/resources/image_builder_templates/ubuntu.yaml"
INFO shaker.openstack.clients.heat [-] New stack: {'id': '07da72e8-bfa2-408b-832d-4777f63f04ad', 'links': [{'rel': 'self', 'href': 'http://10.24.61.255:8004/v1/0574516e37db4961a8862dea82461c97/stacks/shaker_57daf9ce-2cb7-443d-b941-51130d5498ce/07da72e8-bfa2-408b-832d-4777f63f04ad'}]}
INFO shaker.openstack.clients.nova [-] Warning message in instance 02b7ff17-8b17-462e-affc-0fbe186202af console: [   21.488451] cloud-init[1250]: WARNING: apt does not have a stable CLI interface. Use with caution in scripts.
ERROR shaker.engine.image_builder [-] Error while building the image: Guest does not have a console available. (HTTP 404) (Request-ID: req-f8b9ce90-2676-4639-b8b8-57520bd4ff65)
ERROR shaker.engine.image_builder [-] Guest does not have a console available. (HTTP 404) (Request-ID: req-f8b9ce90-2676-4639-b8b8-57520bd4ff65)
ERROR shaker.engine.image_builder Traceback (most recent call last):
ERROR shaker.engine.image_builder   File "/usr/local/lib/python3.5/site-packages/shaker/engine/image_builder.py", line 94, in build_image_with_heat
ERROR shaker.engine.image_builder     nova.wait_server_shutdown(openstack_client.nova, server_id)
ERROR shaker.engine.image_builder   File "/usr/local/lib/python3.5/site-packages/shaker/openstack/clients/nova.py", line 123, in wait_server_shutdown
ERROR shaker.engine.image_builder     _poll_for_status(nova_client, server_id, ['shutoff'])
ERROR shaker.engine.image_builder   File "/usr/local/lib/python3.5/site-packages/shaker/openstack/clients/nova.py", line 102, in _poll_for_status
ERROR shaker.engine.image_builder     err_msg = check_server_console(nova_client, server_id)
ERROR shaker.engine.image_builder   File "/usr/local/lib/python3.5/site-packages/shaker/openstack/clients/nova.py", line 75, in check_server_console
ERROR shaker.engine.image_builder     console = nova_client.servers.get(server_id).get_console_output(len_limit)
ERROR shaker.engine.image_builder   File "/usr/local/lib/python3.5/site-packages/novaclient/v2/servers.py", line 99, in get_console_output
ERROR shaker.engine.image_builder     return self.manager.get_console_output(self, length)
ERROR shaker.engine.image_builder   File "/usr/local/lib/python3.5/site-packages/novaclient/v2/servers.py", line 1669, in get_console_output
ERROR shaker.engine.image_builder     {'length': length})
ERROR shaker.engine.image_builder   File "/usr/local/lib/python3.5/site-packages/novaclient/v2/servers.py", line 1923, in _action_return_resp_and_body
ERROR shaker.engine.image_builder     return self.api.client.post(url, body=body)
ERROR shaker.engine.image_builder   File "/usr/local/lib/python3.5/site-packages/keystoneauth1/adapter.py", line 229, in post
ERROR shaker.engine.image_builder     return self.request(url, 'POST', **kwargs)
ERROR shaker.engine.image_builder   File "/usr/local/lib/python3.5/site-packages/novaclient/client.py", line 80, in request
ERROR shaker.engine.image_builder     raise exceptions.from_response(resp, body, url, method)
ERROR shaker.engine.image_builder novaclient.exceptions.NotFound: Guest does not have a console available. (HTTP 404) (Request-ID: req-f8b9ce90-2676-4639-b8b8-57520bd4ff65)
```

**Comment by msimonin** [comment]
It seems we build our on shaker docker image. A first step would be to update it.

**Comment by rcherrueau** [comment]
Report to openstack/shacker: https://bugs.launchpad.net/shaker/+bug/1800158
