### ISSUE TITLE
undefined variable network_interface

### ISSUE THREAD

**Issue by bvermeul** [BeyondTheClouds/enos#335]
Hi,

I try to use enos deploy with a static provider (existing bare metal machines), but I get the following error 
`TASK [registry : Checking that the vip is free on this host] *******************************************************************************************************************************************************************************************************************
fatal: [enos-0]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'network_interface' is undefined\n\nThe error appears to have been in '/users/bvermeul/myopenstack/venv/lib/python3.5/site-packages/enos/ansible/roles/registry/tasks/install_registry.yml': line 1, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Checking that the vip is free on this host\n  ^ here\n"}
`
I added already this inventory
`[control]
enos-0 ansible_host=192.168.0.3 ansible_ssh_user=root ansible_ssh_private_key_file=/root/.ssh/id_rsa ansible_ssh_common_args='-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null' my_network=enp0s9 enos_devices="['enp0s9']"
[default_group]
enos-0 ansible_host=192.168.0.3 ansible_ssh_user=root ansible_ssh_private_key_file=/root/.ssh/id_rsa ansible_ssh_common_args='-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null' my_network=enp0s9 enos_devices="['enp0s9']"
enos-1 ansible_host=192.168.0.2 ansible_ssh_user=root ansible_ssh_private_key_file=/root/.ssh/id_rsa ansible_ssh_common_args='-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null' my_network=enp9s0f0 enos_devices="['enp9s0f0']"
enos-2 ansible_host=192.168.0.4 ansible_ssh_user=root ansible_ssh_private_key_file=/root/.ssh/id_rsa ansible_ssh_common_args='-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null' my_network=enp9s0f0 enos_devices="['enp9s0f0']"
[network]
enos-1 ansible_host=192.168.0.2 ansible_ssh_user=root ansible_ssh_private_key_file=/root/.ssh/id_rsa ansible_ssh_common_args='-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null' my_network=enp9s0f0 enos_devices="['enp9s0f0']"
[compute]
enos-2 ansible_host=192.168.0.4 ansible_ssh_user=root ansible_ssh_private_key_file=/root/.ssh/id_rsa ansible_ssh_common_args='-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null' my_network=enp9s0f0 enos_devices="['enp9s0f0']"
`
but it keeps saying the same.

I'm not sure if enos_devices is picked up correctly, as the current/env contains this
`rsc:
  compute:
  - !!python/object:enoslib.host.Host
    address: 192.168.0.4
    alias: enos-2
    extra:
      enos_devices: []
    keyfile: /root/.ssh/id_rsa
    port: null
    user: root
`
any idea how I can further debug/solve this ?

thanks,
Brecht

**Comment by msimonin** [comment]
Hi @bvermeul ,

Could you post your configuration file (`reservation.yam`) ? 
We'll first check there.

**Comment by bvermeul** [comment]
Hi, 

`---
# ############################################### #
# Static provider parameter                       #
# ############################################### #
# Example of using yaml anchors
hosts:
  1: &h1
    address: 192.168.0.3
    alias: enos-0
    user: root
    keyfile: /root/.ssh/id_rsa
  2: &h2
    address: 192.168.0.2
    alias: enos-1
    user: root
    keyfile: /root/.ssh/id_rsa
  3: &h3
    address: 192.168.0.4
    alias: enos-2
    user: root
    keyfile: /root/.ssh/id_rsa

resources:
  control:
    - *h1
  network:
    - *h2
  compute:
    - *h3

provider:
  type: static
  networks:
    - start: 192.168.142.3
      end:  192.168.142.119
      cidr: 192.168.142.0/24
      gateway: 192.168.142.1
      dns: 8.8.8.8
      roles: ["network_interface"]
    - start: 192.168.143.3
      end:  192.168.143.119
      cidr: 192.168.143.0/24
      gateway: 192.168.143.1
      dns: 8.8.8.8
      roles: ["neutron_external_interface"]


# ############################################### #
# Inventory to use                                #
# ############################################### #

# This will describe the topology of your services
inventory: inventory

# ############################################### #
# docker registry parameters
# ############################################### #

# A registry will be deployed and used during the deployment
registry:
  type: internal
  #ceph: true
  #ceph_keyring: /home/discovery/.ceph/ceph.client.discovery.keyring
  #ceph_id: discovery
  #ceph_rbd: discovery_kolla_registry/datas
  #ceph_mon_host:
  #  - ceph0.rennes.grid5000.fr
  #  - ceph1.rennes.grid5000.fr
  #  - ceph2.rennes.grid5000.fr

# No registry will be used
# registry:
#         type: none

# Use a registry already deployed
# registry:
#   type: external
#   ip: 192.168.142.253
#   port: 5000


# ############################################### #
# Enos Customizations                             #
# ############################################### #
enable_monitoring: no


# ############################################### #
# Kolla parameters                                #
# ############################################### #
# Repository
kolla_repo: "https://git.openstack.org/openstack/kolla-ansible"
kolla_ref: "stable/queens"

# Vars : globals.yml
kolla:
  kolla_base_distro: "centos"
  kolla_install_type: "source"
  docker_namespace: "beyondtheclouds"
  enable_heat: "no"
`

Brecht

**Comment by msimonin** [comment]
From what I see 
```
provider:
  type: static
  networks:
  - cidr: 192.168.142.0/24
    dns: 8.8.8.8
    end: 192.168.142.119
    gateway: 192.168.142.1
    roles:
    - network_interface
    start: 192.168.142.3
  - cidr: 192.168.143.0/24
    dns: 8.8.8.8
    end: 192.168.143.119
    gateway: 192.168.143.1
    roles:
    - neutron_external_interface
    start: 192.168.143.3
```

So you have to make sure those networks are configured in the target nodes.
EnOS then tries to map those networks to network cards and fill the ansible hostvars variables for you (with the right network card name) in the inventory. The inventory is generated and should contain something like `network_interface=eth1` and `neutron_external_interface=eth2`. If you don't have two NICs configured you can omit `neutron_external_interface`. This also mean that using EnOS, the inventory is generated for you, modifying it has no effect since it's overriden everytime you call `up` or `deploy`.

Note that for other provider (like Grid'5000) all those details are hidden in the provider logic, so you shouldn't have to worry much about network configuration.

**Comment by bvermeul** [comment]
okay, that's clear (I thought the network interfaces were automatically configured). It's much better now, but stops on this:
```RUNNING HANDLER [common : Restart fluentd container] ***************************************************************************************************************************************************************************************************************************
fatal: [enos-1]: FAILED! => {"changed": true, "msg": "'Traceback (most recent call last):\\n  File \"/tmp/ansible_jOKarC/ansible_module_kolla_docker.py\", line 863, in main\\n    result = bool(getattr(dw, module.params.get(\\'action\\'))())\\n  File \"/tmp/ansible_jOKarC/ansible_module_kolla_docker.py\", line 634, in recreate_or_restart_container\\n    self.start_container()\\n  File \"/tmp/ansible_jOKarC/ansible_module_kolla_docker.py\", line 647, in start_container\\n    self.pull_image()\\n  File \"/tmp/ansible_jOKarC/ansible_module_kolla_docker.py\", line 499, in pull_image\\n    repository=image, tag=tag, stream=True\\n  File \"/usr/local/lib/python2.7/dist-packages/docker/api/image.py\", line 400, in pull\\n    self._raise_for_status(response)\\n  File \"/usr/local/lib/python2.7/dist-packages/docker/api/client.py\", line 258, in _raise_for_status\\n    raise create_api_error_from_http_exception(e)\\n  File \"/usr/local/lib/python2.7/dist-packages/docker/errors.py\", line 31, in create_api_error_from_http_exception\\n    raise cls(e, response=response, explanation=explanation)\\nNotFound: 404 Client Error: Not Found (\"manifest for beyondtheclouds/centos-source-fluentd:rocky not found\")\\n'"}
```

I can do a `docker pull beyondtheclouds/centos-source-fluentd`
 which gives
```
docker images
REPOSITORY                              TAG                 IMAGE ID            CREATED             SIZE
beyondtheclouds/centos-source-fluentd   latest              911ffac242ec        2 months ago        551MB
```
but ` beyondtheclouds/centos-source-fluentd:rocky` can not be found it seems.

Any advice on this ?

thanks,
Brecht

**Comment by msimonin** [comment]
Could you give me the output of :
```
enos --version
```
and 
```
enos new 
```

**Comment by bvermeul** [comment]
```
 enos --version
5.0.1
(venv) root@node0:/users/bvermeul/myopenstack# enos new
/users/bvermeul/myopenstack/venv/lib/python3.5/site-packages/enoslib/task.py:93: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  env.update(yaml.load(f))
Traceback (most recent call last):
  File "/users/bvermeul/myopenstack/venv/bin/enos", line 10, in <module>
    sys.exit(main())
  File "/users/bvermeul/myopenstack/venv/lib/python3.5/site-packages/enos/cli.py", line 345, in main
    task(**docopt(task.__doc__, argv=argv))
  File "/users/bvermeul/myopenstack/venv/lib/python3.5/site-packages/enos/cli.py", line 199, in new
    t.new(**kwargs)
  File "/users/bvermeul/myopenstack/venv/lib/python3.5/site-packages/enoslib/task.py", line 48, in decorated
    kwargs["env"] = _make_env(k_env or SYMLINK_NAME)
  File "/users/bvermeul/myopenstack/venv/lib/python3.5/site-packages/enoslib/task.py", line 93, in _make_env
    env.update(yaml.load(f))
  File "/users/bvermeul/myopenstack/venv/lib/python3.5/site-packages/yaml/__init__.py", line 114, in load
    return loader.get_single_data()
  File "/users/bvermeul/myopenstack/venv/lib/python3.5/site-packages/yaml/constructor.py", line 43, in get_single_data
    return self.construct_document(node)
  File "/users/bvermeul/myopenstack/venv/lib/python3.5/site-packages/yaml/constructor.py", line 52, in construct_document
    for dummy in generator:
  File "/users/bvermeul/myopenstack/venv/lib/python3.5/site-packages/yaml/constructor.py", line 399, in construct_yaml_seq
    data.extend(self.construct_sequence(node))
  File "/users/bvermeul/myopenstack/venv/lib/python3.5/site-packages/yaml/constructor.py", line 122, in construct_sequence
    for child in node.value]
  File "/users/bvermeul/myopenstack/venv/lib/python3.5/site-packages/yaml/constructor.py", line 122, in <listcomp>
    for child in node.value]
  File "/users/bvermeul/myopenstack/venv/lib/python3.5/site-packages/yaml/constructor.py", line 97, in construct_object
    data = next(generator)
  File "/users/bvermeul/myopenstack/venv/lib/python3.5/site-packages/yaml/constructor.py", line 593, in construct_python_object
    instance = self.make_python_instance(suffix, node, newobj=True)
  File "/users/bvermeul/myopenstack/venv/lib/python3.5/site-packages/yaml/constructor.py", line 566, in make_python_instance
    cls = self.find_python_name(suffix, node.start_mark)
  File "/users/bvermeul/myopenstack/venv/lib/python3.5/site-packages/yaml/constructor.py", line 538, in find_python_name
    "module %r is not imported" % module_name, mark)
yaml.constructor.ConstructorError: while constructing a Python object
module 'enoslib.host' is not imported
  in "current/env", line 69, column 5
````

**Comment by bvermeul** [comment]
outside of that env
```
root@node0:/users/bvermeul# enos new
/usr/local/lib/python2.7/dist-packages/enoslib/task.py:93: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  env.update(yaml.load(f))
INFO:enoslib.task:- Task new started -
---
# ############################################### #
# Grid'5000 reservation parameters                #
# ############################################### #
provider:
  type: g5k
  job_name: 'enos'
  walltime: '02:00:00'

resources:
  paravance:
    compute: 1
    network: 1
    control: 1


# ############################################### #
# Chameleon reservation parameters                #
# ############################################### #
provider:
  type: chameleonkvm
  key_name: enos_key
  gateway: true
resources:
  m1.medium:
    compute: 1
    network: 1
    control: 1

provider:
  type: chameleonbaremetal
  key_name: 'enos-key'
  walltime: '2:00:00'
  gateway: true
resources:
  compute_haswell:
    control: 1
    network: 1
    compute: 1

# ############################################### #
# Vagrant reservation parameters                  #
# ############################################### #
provider:
  type: vagrant
  backend: libvirt
  box: generic/debian9
resources:
  extra-large:
    control: 1
  medium:
    network: 1
    compute: 1

# ############################################### #
# Static provider parameter                       #
# ############################################### #
# Example of using yaml anchors
hosts:
  1: &h1
    address: 192.168.142.245
    alias: enos-0
    user: root
    keyfile: .vagrant/machines/enos-0/libvirt/private_key
  2: &h2
    address: 192.168.142.244
    alias: enos-1
    user: root
    keyfile: .vagrant/machines/enos-1/libvirt/private_key
  3: &h3
    address: 192.168.142.243
    alias: enos-2
    user: root
    keyfile: .vagrant/machines/enos-2/libvirt/private_key

resources:
  control:
    - *h1
  network:
    - *h2
  compute:
    - *h3

provider:
  type: static
  networks:
    - start: 192.168.142.3
      end:  192.168.142.119
      cidr: 192.168.142.0/24
      gateway: 192.168.142.1
      dns: 8.8.8.8
      roles: ["network_interface"]
    - start: 192.168.143.3
      end:  192.168.143.119
      cidr: 192.168.143.0/24
      gateway: 192.168.143.1
      dns: 8.8.8.8
      roles: ["neutron_external_interface"]


# ############################################### #
# Inventory to use                                #
# ############################################### #

# This will describe the topology of your services
inventory: inventories/inventory.sample

# ############################################### #
# docker registry parameters
# ############################################### #

# A registry will be deployed and used during the deployment
registry:
  type: internal
  #ceph: true
  #ceph_keyring: /home/discovery/.ceph/ceph.client.discovery.keyring
  #ceph_id: discovery
  #ceph_rbd: discovery_kolla_registry/datas
  #ceph_mon_host:
  #  - ceph0.rennes.grid5000.fr
  #  - ceph1.rennes.grid5000.fr
  #  - ceph2.rennes.grid5000.fr

# No registry will be used
# registry:
#         type: none

# Use a registry already deployed
# registry:
#   type: external
#   ip: 192.168.142.253
#   port: 5000


# ############################################### #
# Enos Customizations                             #
# ############################################### #
enable_monitoring: no


# ############################################### #
# Kolla parameters                                #
# ############################################### #
# Repository
kolla_repo: "https://git.openstack.org/openstack/kolla-ansible"
kolla_ref: "stable/queens"

# Vars : globals.yml
kolla:
  kolla_base_distro: "centos"
  kolla_install_type: "source"
  docker_namespace: "beyondtheclouds"
  enable_heat: "no"

INFO:enoslib.task:- Task new finished -
```

**Comment by msimonin** [comment]
Here's what I got: 
```
(brecht-3.5) ➜  /tmp pip install enos
Collecting enos
  Downloading https://files.pythonhosted.org/packages/d9/53/ed6215f23a60934dcf859a2dc7608ea5988e34b29a0780a94439daa9673d/enos-5.0.1-py3-none-any.whl (110kB)
    100% |████████████████████████████████| 112kB 2.1MB/s 
Collecting virtualenv (from enos)
  Using cached https://files.pythonhosted.org/packages/33/5d/314c760d4204f64e4a968275182b7751bd5c3249094757b39ba987dcfb5a/virtualenv-16.4.3-py2.py3-none-any.whl
Collecting GitPython>=2.1.5 (from enos)
  Using cached https://files.pythonhosted.org/packages/fe/e5/fafe827507644c32d6dc553a1c435cdf882e0c28918a5bab29f7fbebfb70/GitPython-2.1.11-py2.py3-none-any.whl
Collecting enoslib<2.1.0,>=2.0.0 (from enos)
  Downloading https://files.pythonhosted.org/packages/44/c4/9c44e011cc793e252fdbdbc5db0d38fea0f870d7df19a5b99a192fdc6dff/enoslib-2.0.3-py3-none-any.whl (93kB)
    100% |████████████████████████████████| 102kB 14.7MB/s 
Collecting docopt<0.7.0,>=0.6.2 (from enos)
Collecting gitdb2>=2.0.0 (from GitPython>=2.1.5->enos)
  Using cached https://files.pythonhosted.org/packages/da/30/a407568aa8d8f25db817cf50121a958722f3fc5f87e3a6fba1f40c0633e3/gitdb2-2.0.5-py2.py3-none-any.whl
Collecting requests<2.19,>=2.18.0 (from enoslib<2.1.0,>=2.0.0->enos)
  Using cached https://files.pythonhosted.org/packages/49/df/50aa1999ab9bde74656c2919d9c0c085fd2b3775fd3eca826012bef76d8c/requests-2.18.4-py2.py3-none-any.whl
Collecting netaddr<0.8,>=0.7 (from enoslib<2.1.0,>=2.0.0->enos)
  Using cached https://files.pythonhosted.org/packages/ba/97/ce14451a9fd7bdb5a397abf99b24a1a6bb7a1a440b019bebd2e9a0dbec74/netaddr-0.7.19-py2.py3-none-any.whl
Collecting python-vagrant>=0.5.15 (from enoslib<2.1.0,>=2.0.0->enos)
Collecting jsonschema<2.7,>=2.6.0 (from enoslib<2.1.0,>=2.0.0->enos)
  Using cached https://files.pythonhosted.org/packages/77/de/47e35a97b2b05c2fadbec67d44cfcdcd09b8086951b331d82de90d2912da/jsonschema-2.6.0-py2.py3-none-any.whl
Collecting ansible<2.6.0,>=2.5.0 (from enoslib<2.1.0,>=2.0.0->enos)
Collecting execo<2.7,>=2.6.2 (from enoslib<2.1.0,>=2.0.0->enos)
Collecting pyyaml<5.2,>=5.1 (from enoslib<2.1.0,>=2.0.0->enos)
Collecting smmap2>=2.0.0 (from gitdb2>=2.0.0->GitPython>=2.1.5->enos)
  Using cached https://files.pythonhosted.org/packages/55/d2/866d45e3a121ee15a1dc013824d58072fd5c7799c9c34d01378eb262ca8f/smmap2-2.0.5-py2.py3-none-any.whl
Collecting idna<2.7,>=2.5 (from requests<2.19,>=2.18.0->enoslib<2.1.0,>=2.0.0->enos)
  Using cached https://files.pythonhosted.org/packages/27/cc/6dd9a3869f15c2edfab863b992838277279ce92663d334df9ecf5106f5c6/idna-2.6-py2.py3-none-any.whl
Collecting chardet<3.1.0,>=3.0.2 (from requests<2.19,>=2.18.0->enoslib<2.1.0,>=2.0.0->enos)
  Using cached https://files.pythonhosted.org/packages/bc/a9/01ffebfb562e4274b6487b4bb1ddec7ca55ec7510b22e4c51f14098443b8/chardet-3.0.4-py2.py3-none-any.whl
Collecting urllib3<1.23,>=1.21.1 (from requests<2.19,>=2.18.0->enoslib<2.1.0,>=2.0.0->enos)
  Using cached https://files.pythonhosted.org/packages/63/cb/6965947c13a94236f6d4b8223e21beb4d576dc72e8130bd7880f600839b8/urllib3-1.22-py2.py3-none-any.whl
Collecting certifi>=2017.4.17 (from requests<2.19,>=2.18.0->enoslib<2.1.0,>=2.0.0->enos)
  Using cached https://files.pythonhosted.org/packages/60/75/f692a584e85b7eaba0e03827b3d51f45f571c2e793dd731e598828d380aa/certifi-2019.3.9-py2.py3-none-any.whl
Requirement already satisfied: setuptools in /home/msimonin/.pyenv/versions/3.6.5/envs/brecht-3.5/lib/python3.6/site-packages (from ansible<2.6.0,>=2.5.0->enoslib<2.1.0,>=2.0.0->enos) (40.8.0)
Collecting jinja2 (from ansible<2.6.0,>=2.5.0->enoslib<2.1.0,>=2.0.0->enos)
  Using cached https://files.pythonhosted.org/packages/7f/ff/ae64bacdfc95f27a016a7bed8e8686763ba4d277a78ca76f32659220a731/Jinja2-2.10-py2.py3-none-any.whl
Collecting paramiko (from ansible<2.6.0,>=2.5.0->enoslib<2.1.0,>=2.0.0->enos)
  Using cached https://files.pythonhosted.org/packages/cf/ae/94e70d49044ccc234bfdba20114fa947d7ba6eb68a2e452d89b920e62227/paramiko-2.4.2-py2.py3-none-any.whl
Collecting cryptography (from ansible<2.6.0,>=2.5.0->enoslib<2.1.0,>=2.0.0->enos)
  Using cached https://files.pythonhosted.org/packages/5b/12/b0409a94dad366d98a8eee2a77678c7a73aafd8c0e4b835abea634ea3896/cryptography-2.6.1-cp34-abi3-manylinux1_x86_64.whl
Collecting MarkupSafe>=0.23 (from jinja2->ansible<2.6.0,>=2.5.0->enoslib<2.1.0,>=2.0.0->enos)
  Using cached https://files.pythonhosted.org/packages/b2/5f/23e0023be6bb885d00ffbefad2942bc51a620328ee910f64abe5a8d18dd1/MarkupSafe-1.1.1-cp36-cp36m-manylinux1_x86_64.whl
Collecting bcrypt>=3.1.3 (from paramiko->ansible<2.6.0,>=2.5.0->enoslib<2.1.0,>=2.0.0->enos)
  Using cached https://files.pythonhosted.org/packages/d0/79/79a4d167a31cc206117d9b396926615fa9c1fdbd52017bcced80937ac501/bcrypt-3.1.6-cp34-abi3-manylinux1_x86_64.whl
Collecting pynacl>=1.0.1 (from paramiko->ansible<2.6.0,>=2.5.0->enoslib<2.1.0,>=2.0.0->enos)
  Using cached https://files.pythonhosted.org/packages/27/15/2cd0a203f318c2240b42cd9dd13c931ddd61067809fee3479f44f086103e/PyNaCl-1.3.0-cp34-abi3-manylinux1_x86_64.whl
Collecting pyasn1>=0.1.7 (from paramiko->ansible<2.6.0,>=2.5.0->enoslib<2.1.0,>=2.0.0->enos)
  Using cached https://files.pythonhosted.org/packages/7b/7c/c9386b82a25115cccf1903441bba3cbadcfae7b678a20167347fa8ded34c/pyasn1-0.4.5-py2.py3-none-any.whl
Collecting asn1crypto>=0.21.0 (from cryptography->ansible<2.6.0,>=2.5.0->enoslib<2.1.0,>=2.0.0->enos)
  Using cached https://files.pythonhosted.org/packages/ea/cd/35485615f45f30a510576f1a56d1e0a7ad7bd8ab5ed7cdc600ef7cd06222/asn1crypto-0.24.0-py2.py3-none-any.whl
Collecting six>=1.4.1 (from cryptography->ansible<2.6.0,>=2.5.0->enoslib<2.1.0,>=2.0.0->enos)
  Using cached https://files.pythonhosted.org/packages/73/fb/00a976f728d0d1fecfe898238ce23f502a721c0ac0ecfedb80e0d88c64e9/six-1.12.0-py2.py3-none-any.whl
Collecting cffi!=1.11.3,>=1.8 (from cryptography->ansible<2.6.0,>=2.5.0->enoslib<2.1.0,>=2.0.0->enos)
  Using cached https://files.pythonhosted.org/packages/20/f7/87b62a8895bf7c93e907b05b97bc4459c81a38a61151f03a6eae13d863aa/cffi-1.12.2-cp36-cp36m-manylinux1_x86_64.whl
Collecting pycparser (from cffi!=1.11.3,>=1.8->cryptography->ansible<2.6.0,>=2.5.0->enoslib<2.1.0,>=2.0.0->enos)
Installing collected packages: virtualenv, smmap2, gitdb2, GitPython, idna, chardet, urllib3, certifi, requests, netaddr, python-vagrant, jsonschema, MarkupSafe, jinja2, pycparser, cffi, six, bcrypt, pynacl, pyasn1, asn1crypto, cryptography, paramiko, pyyaml, ansible, execo, enoslib, docopt, enos
Successfully installed GitPython-2.1.11 MarkupSafe-1.1.1 ansible-2.5.15 asn1crypto-0.24.0 bcrypt-3.1.6 certifi-2019.3.9 cffi-1.12.2 chardet-3.0.4 cryptography-2.6.1 docopt-0.6.2 enos-5.0.1 enoslib-2.0.3 execo-2.6.4 gitdb2-2.0.5 idna-2.6 jinja2-2.10 jsonschema-2.6.0 netaddr-0.7.19 paramiko-2.4.2 pyasn1-0.4.5 pycparser-2.19 pynacl-1.3.0 python-vagrant-0.5.15 pyyaml-5.1 requests-2.18.4 six-1.12.0 smmap2-2.0.5 urllib3-1.22 virtualenv-16.4.3
```

```
(brecht-3.5) ➜  /tmp enos --version
5.0.1
```

```
(brecht-3.5) ➜  /tmp enos new
INFO:enoslib.task:- Task new started -
---
# ############################################### #
# VMonG5K reservation parameters                  #
# ############################################### #
provider:
  type: vmong5k
  job_name: 'enos'
  walltime: '02:00:00'

resources:
  paravance:
    network: 1
    control: 1
  parasilo:
    compute: 1

virt_image: /grid5000/virt-images/debian9-x64-base.qcow2

# ############################################### #
# Grid'5000 reservation parameters                #
# ############################################### #
provider:
  type: g5k
  job_name: 'enos'
  walltime: '02:00:00'

resources:
  paravance:
    compute: 1
    network: 1
    control: 1


# ############################################### #
# Chameleon reservation parameters                #
# ############################################### #
provider:
  type: chameleonkvm
  key_name: enos_key
  gateway: true
resources:
  m1.medium:
    compute: 1
    network: 1
    control: 1

provider:
  type: chameleonbaremetal
  key_name: 'enos-key'
  walltime: '2:00:00'
  gateway: true
resources:
  compute_haswell:
    control: 1
    network: 1
    compute: 1

# ############################################### #
# Vagrant reservation parameters                  #
# ############################################### #
provider:
  type: vagrant
  backend: libvirt
  box: generic/debian9
resources:
  extra-large:
    control: 1
  medium:
    network: 1
    compute: 1

# ############################################### #
# Static provider parameter                       #
# ############################################### #
# Example of using yaml anchors
hosts:
  1: &h1
    address: 192.168.142.245
    alias: enos-0
    user: root
    keyfile: .vagrant/machines/enos-0/libvirt/private_key
  2: &h2
    address: 192.168.142.244
    alias: enos-1
    user: root
    keyfile: .vagrant/machines/enos-1/libvirt/private_key
  3: &h3
    address: 192.168.142.243
    alias: enos-2
    user: root
    keyfile: .vagrant/machines/enos-2/libvirt/private_key

resources:
  control:
    - *h1
  network:
    - *h2
  compute:
    - *h3

provider:
  type: static
  networks:
    - start: 192.168.142.3
      end:  192.168.142.119
      cidr: 192.168.142.0/24
      gateway: 192.168.142.1
      dns: 8.8.8.8
      roles: ["network_interface"]
    - start: 192.168.143.3
      end:  192.168.143.119
      cidr: 192.168.143.0/24
      gateway: 192.168.143.1
      dns: 8.8.8.8
      roles: ["neutron_external_interface"]


# ############################################### #
# Inventory to use                                #
# ############################################### #

# This will describe the topology of your services
inventory: inventories/inventory.sample

# ############################################### #
# docker registry parameters
# ############################################### #

# A registry will be deployed and used during the deployment
registry:
  type: internal
  #ceph: true
  #ceph_keyring: /home/discovery/.ceph/ceph.client.discovery.keyring
  #ceph_id: discovery
  #ceph_rbd: discovery_kolla_registry/datas
  #ceph_mon_host:
  #  - ceph0.rennes.grid5000.fr
  #  - ceph1.rennes.grid5000.fr
  #  - ceph2.rennes.grid5000.fr

# No registry will be used
# registry:
#	  type: none

# Use a registry already deployed
# registry:
#   type: external
#   ip: 192.168.142.253
#   port: 5000


# ############################################### #
# Enos Customizations                             #
# ############################################### #
enable_monitoring: no


# ############################################### #
# Kolla parameters                                #
# ############################################### #
# Repository
kolla_repo: "https://git.openstack.org/openstack/kolla-ansible"
kolla_ref: "stable/rocky"

# Vars : globals.yml
kolla:
  kolla_base_distro: "centos"
  kolla_install_type: "source"
  enable_heat: "no"

INFO:enoslib.task:- Task new finished -
```

So I suspect your venv to not be up-to-date.  Could you recreate-it ?
Also can you make sure that in your conf there is:

```
# Repository
kolla_repo: "https://git.openstack.org/openstack/kolla-ansible"
kolla_ref: "stable/rocky"

# Vars : globals.yml
kolla:
  kolla_base_distro: "centos"
  kolla_install_type: "source"
  enable_heat: "no"
```

**Comment by bvermeul** [comment]
Hi,

yes, much better now.
I recreated env, used the new reservation.yaml and now it finished.
Thanks a lot for your help !
Brecht

**Comment by msimonin** [comment]
Hi,

Glad to hear :)
If you think the documentation lack some information or is confusing at some point, don't hesitate to mention it here also.
